-- 简历工坊 · 模板/词库/meta 种子数据（从线上旧库导出，2026-09-18）
-- 幂等：可重复执行；已存在的按主键/唯一键更新。请在跑完 docs/schema.sql 之后执行本文件。
-- 内容：tpl_professions=30 行，tpl_glossary=56 行，tpl_meta=5 行

BEGIN;

-- 1) 职业模板
INSERT INTO tpl_professions (slug,title,industry,summary,sections,sample,theme,sort) VALUES
  ('structural-engineer', '结构开发工程师', '制造业', '适合家具/五金/铝件结构岗。重点写：负责过什么品类、图纸量、改善带来的工时或成本变化。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"宁波","name":"张伟","site":"","birth":"1995-06","email":"zhangwei@example.com","phone":"138 0000 0001","photo":"","years":"5","intent":"结构开发工程师"},"work":[{"end":"至今","role":"结构开发工程师","start":"2021-04","bullets":["负责铝合金折叠椅、特斯林躺椅结构方案设计与图纸输出，年均交付 40+ 套（示例，换成你的真实量级）","主导管件折弯工装改良，单件工时 62 秒降至 47 秒，年节约约 3600 工时","建立铝型材/铁型材标准库与 BOM 核对规则，图号差错率下降约 38%"],"company":"某户外家具有限公司"},{"end":"2021-03","role":"助理结构工程师","start":"2018-03","bullets":["跟进 12 款椅类新品打样到量产，样品一次通过率提升至 86%","编制零件表与制造令，配合车间处理现场结构变更 60+ 项"],"company":"某五金制品有限公司"}],"certs":[{"org":"示例证书","date":"2019-05","name":"SolidWorks 认证 CSWA"}],"links":[],"awards":["年度改善提案二等奖（示例）"],"skills":[{"name":"SolidWorks","level":88},{"name":"公差与GD&T","level":78},{"name":"铝/铁型材与焊接工艺","level":82}],"summary":"5 年户外家具与五金结构开发经验，独立负责从方案、图纸、BOM 到量产导入全流程；擅长以结构简化换取工时与材料成本下降。示例段落，请改成你自己的年限与代表成果。","projects":[{"end":"2023-09","desc":"把整椅重量降 12% 同时保持承载标准，通过料厚重分布与型材截面优化实现，单件材料成本下降 7.4%（示例）","name":"折叠椅轻量化项目","role":"结构负责人","start":"2023-03"}],"education":[{"end":"2017-06","note":"主修工程制图、材料力学、公差与测量；示例数据，请替换","major":"机械设计制造及其自动化","start":"2013-09","degree":"本科","school":"宁波工程学院"}],"skillTags":["DFMEA","BOM拆解","钣金展开","模具评审","样机试制"]}$rqjson$::jsonb, $rqjson${"lh":1.5,"dens":0.95,"font":"sans","head":"bar","style":"modern","accent":"#2f5c8f","layout":"default"}$rqjson$::jsonb, 10),
  ('mold-designer', '模具设计工程师', '制造业', '冲压/注塑模具岗。写清模具类型、套数、寿命与试模问题解决率。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"台州","name":"李强","site":"","birth":"1992-11","email":"liqiang@example.com","phone":"139 0000 0002","photo":"","years":"8","intent":"模具设计工程师"},"work":[{"end":"至今","role":"冲压模具设计师","start":"2017-07","bullets":["累计完成连续模、单工程模设计 180+ 套，覆盖 0.5–6.0mm 板厚（示例量级）","导入 CAE 回弹补偿后试模次数由平均 4.2 次降至 2.1 次","沉淀标准件库与镶件结构，模具设计工时下降 25%"],"company":"某模具科技有限公司"},{"end":"2017-06","role":"模具钳工转设计","start":"2013-07","bullets":["负责 40 副在产模具保养与改模，非计划停机减少 30%"],"company":"某汽配有限公司"}],"certs":[{"org":"示例","date":"2020-12","name":"模具设计工程师中级职称"}],"links":[],"awards":[],"skills":[{"name":"UG/NX 模具设计","level":90},{"name":"冲压工艺与排样","level":85},{"name":"CAE 成形分析","level":70}],"summary":"8 年冲压模具设计与现场经验，能独立完成从 DFM 评审到量产移交；擅长用结构标准化压缩设计与试模周期。示例文字，请替换。","projects":[{"end":"2022-12","desc":"解决开裂与回弹问题，尺寸合格率从 78% 提升至 96%（示例）","name":"高张力钢热成型件模具开发","role":"设计主导","start":"2022-04"}],"education":[{"end":"2013-06","note":"示例数据","major":"模具设计与制造","start":"2010-09","degree":"大专","school":"浙江机电职业技术学院"}],"skillTags":["连续模","回弹补偿","镶件结构","试模跟进","DFM"]}$rqjson$::jsonb, $rqjson${"lh":1.55,"dens":1,"font":"sans","head":"underline","style":"sidebar","accent":"#244a75","layout":"sidebar"}$rqjson$::jsonb, 20),
  ('foreign-sales', '外贸业务员', '贸易', '欧美市场业务岗。核心是业绩数字：成交额、新客户数、复购率、回款。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"宁波","name":"王芳","site":"","birth":"1994-03","email":"wangfang@example.com","phone":"137 0000 0003","photo":"","years":"6","intent":"外贸业务员（欧美市场）"},"work":[{"end":"至今","role":"外贸业务员","start":"2019-05","bullets":["独立开发欧美客户 32 家，年度成交金额约 780 万美元（示例数字）","老客户年复购率 68%，坏账为零，平均回款周期 26 天","主导展会 + 开发信 + 社媒三线获客，单个新客户获取成本下降 22%"],"company":"某家居用品进出口公司"},{"end":"2019-04","role":"外贸跟单","start":"2016-07","bullets":["跟过 150+ 个订单，准时出运率 98%，客诉率低于 1.2%"],"company":"某轻工国际贸易有限公司"}],"certs":[{"org":"示例","date":"2018-06","name":"CATTI 三级笔译"}],"links":[],"awards":["年度销售冠军（示例）"],"skills":[{"name":"英语商务谈判","level":90},{"name":"客户开发与跟进","level":88},{"name":"单证与结汇","level":80}],"summary":"6 年家居类外贸经验，熟悉欧美客户开发节奏与合规结汇流程；擅长用数据管理客户漏斗，把线索转成订单。示例文字。","projects":[{"end":"2023-06","desc":"完成价格与年度返利结构调整，锁定 240 万美元订单量（示例）","name":"北美大客户年度框架谈判","role":"主谈","start":"2023-01"}],"education":[{"end":"2016-06","note":"专业八级（示例）","major":"国际经济与贸易","start":"2012-09","degree":"本科","school":"浙江外国语学院"}],"skillTags":["阿里巴巴国际站","展会获客","信用证","FOB/CIF","PI/CI"]}$rqjson$::jsonb, $rqjson${"lh":1.55,"dens":0.98,"font":"sans","head":"bar","style":"banner","accent":"#1f6f5c","layout":"banner"}$rqjson$::jsonb, 30),
  ('doc-clerk', '单证 / 外贸跟单', '贸易', '写熟流程节点与差错率，突出准、稳、零事故。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"舟山","name":"刘敏","site":"","birth":"1996-01","email":"liumin@example.com","phone":"136 0000 0004","photo":"","years":"4","intent":"外贸单证 / 跟单"},"work":[{"end":"至今","role":"单证员","start":"2020-08","bullets":["年均制单 1200+ 份（发票/装箱单/产地证/信用证），一次审单通过率 99.3%","核对信用证软条款 300+ 份，拦截 11 处高风险条款，避免拒付损失","与货代、报关行建立节点表，平均出运周期缩短 3 天（示例）"],"company":"某供应链管理有限公司"},{"end":"2020-07","role":"跟单助理","start":"2018-07","bullets":["跟进打样、验货、订舱全流程，订单准时交付率 97%"],"company":"某外贸公司"}],"certs":[{"org":"示例","date":"2019-05","name":"国际贸易单证员"}],"links":[],"awards":[],"skills":[{"name":"信用证审单","level":88},{"name":"报关与拖车协调","level":80},{"name":"Excel 数据核对","level":85}],"summary":"4 年单证与跟单经验，做事以零差错为目标；熟悉信用证条款风险点与出运全节点协调。示例文字。","projects":[],"education":[{"end":"2018-06","note":"示例","major":"国际商务","start":"2014-09","degree":"本科","school":"浙江水利水电学院"}],"skillTags":["UCP600","产地证","装箱单","L/C","ERP"]}$rqjson$::jsonb, $rqjson${"lh":1.6,"dens":1,"font":"serif","head":"underline","style":"classic","accent":"#2f5c8f","layout":"default"}$rqjson$::jsonb, 40),
  ('pc-planner', '生产计划 / 生管', '制造业', 'PMC 岗。写排产逻辑、达成率、库存周转与异常处理机制。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"嘉兴","name":"陈刚","site":"","birth":"1991-08","email":"chengang@example.com","phone":"135 0000 0005","photo":"","years":"9","intent":"生产计划（PMC）"},"work":[{"end":"至今","role":"生产计划主管","start":"2018-04","bullets":["统筹 3 个车间、月均 6 万件排产，订单准时交付率从 83% 提升至 96%（示例）","建立产能负荷表与安全库存规则，成品库存周转天数由 34 天降至 21 天","主导周计划-日派工-异常停线响应机制，缺料停线次数下降 62%"],"company":"某家具制造有限公司"},{"end":"2018-03","role":"生产计划员","start":"2012-07","bullets":["负责 40+ SKU 排产与物料跟催，插单响应时间从 2 天缩短到 4 小时"],"company":"某电子加工厂"}],"certs":[{"org":"示例","date":"2016-11","name":"初级物流师"}],"links":[],"awards":[],"skills":[{"name":"产能与负荷平衡","level":90},{"name":"ERP/MES 计划模块","level":85},{"name":"Excel 建模","level":88}],"summary":"9 年制造业 PMC 经验，从排产到齐套到异常闭环都能自己拉通；习惯用数据看板和例会机制管交期。示例文字。","projects":[{"end":"2022-11","desc":"替代 Excel 手工排产，计划编制耗时下降 70%（示例）","name":"MES 排产模块上线","role":"业务负责人","start":"2022-03"}],"education":[{"end":"2012-06","note":"示例","major":"工业工程","start":"2008-09","degree":"本科","school":"合肥工业大学"}],"skillTags":["MRP","S&OP","交期管理","齐套率","瓶颈工序"]}$rqjson$::jsonb, $rqjson${"lh":1.6,"dens":1,"font":"sans","head":"underline","style":"timeline","accent":"#8a5a19","layout":"default","timeline":true}$rqjson$::jsonb, 50),
  ('qa-qc', '品质工程师 QA/QC', '制造业', '品质岗。写体系、客诉、过程能力与改善项目收益。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"苏州","name":"赵倩","site":"","birth":"1993-12","email":"zhaoqian@example.com","phone":"134 0000 0006","photo":"","years":"7","intent":"品质工程师（QA/QC）"},"work":[{"end":"至今","role":"品质工程师","start":"2019-02","bullets":["客诉件数同比下降 45%，客诉响应时效控制在 24 小时内（示例）","推动关键工序 SPC 管控，CPK 由 1.02 提升至 1.47","主导 ISO 9001 年度审核与验厂 12 次，零严重不符合项"],"company":"某金属制品有限公司"},{"end":"2019-01","role":"IPQC 检验员","start":"2015-07","bullets":["编制 28 份检验作业指导书，来料批次合格率提升至 98.5%"],"company":"某家具厂"}],"certs":[{"org":"示例","date":"2018-09","name":"内审员资格证 ISO9001"}],"links":[],"awards":[],"skills":[{"name":"8D / 5Why 分析","level":90},{"name":"SPC 与 CPK 改善","level":85},{"name":"供应商质量管理","level":78}],"summary":"7 年制造现场品质经验，熟悉从进料到出货全链路管控与客户验厂要求；改善以数据说话。示例文字。","projects":[{"end":"2022-10","desc":"焊渣与气孔不良率 3.8% 降至 0.9%，年减少返工成本约 30 万元（示例）","name":"焊接缺陷攻关小组","role":"组长","start":"2022-05"}],"education":[{"end":"2015-06","note":"示例","major":"质量管理工程","start":"2011-09","degree":"本科","school":"江苏大学"}],"skillTags":["ISO9001","FMEA","MSA","来料检验","验厂"]}$rqjson$::jsonb, $rqjson${"lh":1.55,"dens":1,"font":"sans","head":"underline","style":"sidebar","accent":"#2b5f7a","layout":"sidebar"}$rqjson$::jsonb, 60),
  ('buyer', '采购工程师 / 专员', '供应链', '采购岗。写降本、供应商管理、交期与合规。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"杭州","name":"孙浩","site":"","birth":"1990-04","email":"sunhao@example.com","phone":"133 0000 0007","photo":"","years":"10","intent":"采购工程师"},"work":[{"end":"至今","role":"采购工程师","start":"2016-05","bullets":["年采购额约 1.6 亿元，综合降本 6.8%（示例）","开发并认证铝型材、粉末涂料供应商 24 家，双源覆盖率 82%","建立到料准时率与批次不良率双看板，来料准时率提升至 96%"],"company":"某家居用品集团"},{"end":"2016-04","role":"采购专员","start":"2011-07","bullets":["负责标准件与外协加工采购，紧急插单交付满足率 99%"],"company":"某五金公司"}],"certs":[{"org":"示例","date":"2015-06","name":"采购师（三级）"}],"links":[],"awards":[],"skills":[{"name":"成本分析与比价议价","level":88},{"name":"供应商评审与考核","level":85},{"name":"ERP / SRM 系统","level":80}],"summary":"10 年制造业采购经验，管过钢材、铝型材、塑料与五金标准件多个品类；擅长用成本结构拆解而不是单纯压价来降本。示例文字。","projects":[],"education":[{"end":"2011-06","note":"示例","major":"供应链管理","start":"2007-09","degree":"本科","school":"浙江工商大学"}],"skillTags":["询比价","年度框架","VMI","来料合格率","交期跟催"]}$rqjson$::jsonb, $rqjson${"lh":1.6,"dens":1,"font":"serif","head":"underline","style":"classic","accent":"#3b5c2f","layout":"default"}$rqjson$::jsonb, 70),
  ('pm', '项目经理', '项目管理', '写项目规模、预算/进度控制、跨部门协调机制与交付结果。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"上海","name":"周磊","site":"","birth":"1988-09","email":"zhouleia@example.com","phone":"138 0000 0008","photo":"","years":"12","intent":"项目经理"},"work":[{"end":"至今","role":"项目经理","start":"2018-06","bullets":["并行管理 6 个项目、总合同额 4200 万元，按期交付率 92%（示例）","建立风险登记册与周例会机制，重大变更响应周期从 7 天降至 2 天","带 18 人跨职能团队（研发/工艺/采购/品质），人力利用率提升至 88%"],"company":"某智能制造公司"},{"end":"2018-05","role":"项目工程师","start":"2014-07","bullets":["负责 3 个新客户项目从报价到量产导入，一次验收通过率 100%"],"company":"某装备有限公司"}],"certs":[{"org":"示例","date":"2019-03","name":"PMP 认证"}],"links":[],"awards":[],"skills":[{"name":"项目计划与WBS","level":90},{"name":"风险与变更管理","level":85},{"name":"跨部门沟通","level":88}],"summary":"12 年制造与智能化项目管理经验，管过从报价、开发到量产交付的全周期；习惯把进度、成本、风险三张表同时看。示例文字。","projects":[{"end":"2022-12","desc":"合同额 1300 万，提前 12 天交付，毛利率超目标 4.6 个百分点（示例）","name":"智能产线交付项目","role":"项目负责人","start":"2022-02"}],"education":[{"end":"2014-06","note":"示例","major":"项目管理","start":"2011-09","degree":"硕士","school":"上海理工大学"}],"skillTags":["PMP","甘特图","里程碑","EVM挣值","敏捷"]}$rqjson$::jsonb, $rqjson${"lh":1.6,"dens":1.02,"font":"serif","head":"underline","style":"corporate","accent":"#2f3f8f","layout":"banner"}$rqjson$::jsonb, 80),
  ('warehouse', '仓管 / 物流专员', '供应链', '写库位管理、准确率、出入库量与盘点结果。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"金华","name":"吴俊","site":"","birth":"1993-02","email":"wujun@example.com","phone":"137 0000 0009","photo":"","years":"7","intent":"仓库管理 / 物流专员"},"work":[{"end":"至今","role":"仓库主管","start":"2019-01","bullets":["管理 8000 ㎡ 仓库、6200 个 SKU，日出入库 3200 件（示例）","库存账实一致率从 94% 提升到 99.5%，月度盘点差异金额下降 76%","推行 ABC 分区与波次拣货，人均拣货效率提升 35%"],"company":"某物流有限公司"},{"end":"2018-12","role":"仓管员","start":"2014-07","bullets":["负责五金件收发与呆滞料预警，呆滞库存下降 40 万元"],"company":"某制造企业"}],"certs":[{"org":"示例","date":"2017-04","name":"叉车司机证"}],"links":[],"awards":[],"skills":[{"name":"WMS 系统","level":86},{"name":"库位规划","level":82},{"name":"叉车作业","level":80}],"summary":"7 年仓储物流现场经验，管过 SKU 多、周转快的成品与五金件仓库；账实一致和库位利用率是我最在意的两件事。示例文字。","projects":[],"education":[{"end":"2014-06","note":"示例","major":"物流管理","start":"2011-09","degree":"大专","school":"浙江交通职业技术学院"}],"skillTags":["先进先出","循环盘点","5S","波次拣货","装卸安全"]}$rqjson$::jsonb, $rqjson${"lh":1.7,"dens":1.08,"font":"sans","head":"plain","style":"minimal","accent":"#1c1c1e","layout":"default"}$rqjson$::jsonb, 90),
  ('worker', '生产作业员 / 技工', '制造业', '技能型岗位写设备、工艺、产量、良率与安全记录。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"宁波","name":"郑涛","site":"","birth":"1990-07","email":"zhengtao@example.com","phone":"136 0000 0010","photo":"","years":"13","intent":"生产技工（焊接 / 装配）"},"work":[{"end":"至今","role":"氩弧焊工","start":"2015-03","bullets":["日均完成铝件焊接 260 件，一次检验合格率 99.2%（示例）","带徒弟 6 名，班组整体不良率由 2.4% 降至 1.1%","连续 5 年零工伤事故，参与 3 项工装改善提案"],"company":"某金属制品厂"},{"end":"2015-02","role":"装配工","start":"2008-07","bullets":["流水线装配与自检，全年产量达标率 101%"],"company":"某家具厂"}],"certs":[{"org":"示例","date":"2013-05","name":"焊工操作证（氩弧焊）"}],"links":[],"awards":["技能比武二等奖（示例）"],"skills":[{"name":"氩弧焊（铝）","level":92},{"name":"图纸识读","level":80},{"name":"工装夹具使用","level":78}],"summary":"13 年一线制造经验，铝件焊接与装配都做得熟，习惯按图纸和首件自检控制质量，不靠返工。示例文字。","projects":[],"education":[{"end":"2008-06","note":"示例","major":"焊接技术","start":"2005-09","degree":"中专/高中","school":"宁波技师学院"}],"skillTags":["铝合金焊接","铆接","打磨","首件自检","安全生产"]}$rqjson$::jsonb, $rqjson${"lh":1.5,"dens":0.95,"font":"sans","head":"bar","style":"modern","accent":"#445b77","layout":"default"}$rqjson$::jsonb, 100),
  ('hr-admin', '行政人事专员', '职能', '写招聘达成、员工关系、制度落地与事务效率。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"杭州","name":"孙悦","site":"","birth":"1994-10","email":"sunyue@example.com","phone":"135 0000 0011","photo":"","years":"6","intent":"人事行政专员 / 主管"},"work":[{"end":"至今","role":"人事行政主管","start":"2019-07","bullets":["年招聘到岗 130 人，一线岗位到岗周期由 21 天压缩至 11 天（示例）","重构考勤与薪酬核算流程，月度核算差错归零，出表时间提前 3 天","落地员工手册与入离职流程，主动离职率下降 8 个百分点"],"company":"某制造企业"},{"end":"2019-06","role":"行政专员","start":"2016-07","bullets":["负责办公资产与会议后勤，年降本 12 万元"],"company":"某服务公司"}],"certs":[{"org":"示例","date":"2018-11","name":"人力资源管理师（四级）"}],"links":[],"awards":[],"skills":[{"name":"招聘与面试组织","level":85},{"name":"薪酬考勤核算","level":82},{"name":"员工关系","level":80}],"summary":"6 年制造业人事行政经验，招聘、考勤薪酬、员工关系全流程都能独立跑；做事讲流程也讲落地速度。示例文字。","projects":[],"education":[{"end":"2016-06","note":"示例","major":"人力资源管理","start":"2012-09","degree":"本科","school":"浙江树人大学"}],"skillTags":["社保公积金","劳动合同","绩效台账","培训组织","公文写作"]}$rqjson$::jsonb, $rqjson${"lh":1.5,"dens":1,"font":"serif","head":"underline","style":"magazine","accent":"#7a3f5c","layout":"magazine"}$rqjson$::jsonb, 110),
  ('accountant', '财务会计', '职能', '写核算范围、报表准时率、税务与成本控制。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"绍兴","name":"何静","site":"","birth":"1991-05","email":"hejing@example.com","phone":"133 0000 0012","photo":"","years":"11","intent":"会计 / 财务主管"},"work":[{"end":"至今","role":"财务主管","start":"2017-04","bullets":["负责 3 套账套核算与月度报表，报表准时率 100%，汇算清缴零调整（示例）","搭建成本分摊模型，产品毛利核算精度提升，识别并清理长期挂账 260 万元","配合外审与税务稽查 4 次，均无重大调整事项"],"company":"某进出口公司"},{"end":"2017-03","role":"总账会计","start":"2012-07","bullets":["应收应付与发票管理，逾期账款回收率提升至 96%"],"company":"某制造公司"}],"certs":[{"org":"示例","date":"2020-09","name":"中级会计师"}],"links":[],"awards":[],"skills":[{"name":"全盘账务处理","level":90},{"name":"税务申报与筹划","level":85},{"name":"Excel 财务建模","level":86}],"summary":"11 年制造业与外贸财务经验，能独立带全盘账务、报表与税务申报；重视数据准确性与业务口径统一。示例文字。","projects":[],"education":[{"end":"2012-06","note":"示例","major":"会计学","start":"2008-09","degree":"本科","school":"浙江财经大学"}],"skillTags":["金蝶/用友","增值税","成本核算","出口退税","内控流程"]}$rqjson$::jsonb, $rqjson${"lh":1.7,"dens":1.08,"font":"sans","head":"plain","style":"minimal","accent":"#35566b","layout":"default"}$rqjson$::jsonb, 120),
  ('sales', '销售顾问 / 客户经理', '销售', '写业绩指标完成率、客户数、客单价与续约。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"温州","name":"许阳","site":"","birth":"1995-12","email":"xuyang@example.com","phone":"139 0000 0013","photo":"","years":"5","intent":"销售顾问 / 客户经理"},"work":[{"end":"至今","role":"区域销售","start":"2020-02","bullets":["年回款 960 万元，指标完成率 118%，区域排名 2/26（示例）","新开经销商 19 家，老客户年续约率 74%","牵头两场产品推介会，单场转化率 27%"],"company":"某建材公司"},{"end":"2020-01","role":"门店销售","start":"2017-07","bullets":["个人客单价由 1200 元提升至 1850 元，连续 8 个月销冠"],"company":"某零售品牌"}],"certs":[],"links":[],"awards":["年度销售之星（示例）"],"skills":[{"name":"客户开发与谈判","level":88},{"name":"渠道管理","level":80},{"name":"数据复盘","level":78}],"summary":"5 年 B2B 与门店销售经验，能自己找线索、谈价、催回款；习惯每周做漏斗复盘而不只看当月数字。示例文字。","projects":[],"education":[{"end":"2017-06","note":"示例","major":"市场营销","start":"2013-09","degree":"本科","school":"温州大学"}],"skillTags":["陌生拜访","招投标","经销商管理","CRM","回款跟进"]}$rqjson$::jsonb, $rqjson${"lh":1.55,"dens":0.98,"font":"sans","head":"bar","style":"banner","accent":"#8f3f2f","layout":"banner"}$rqjson$::jsonb, 130),
  ('fresh-grad', '应届生通用', '通用', '无工作经验时用课程项目、实习、竞赛与社团撑住内容量。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"杭州","name":"林小雨","site":"","birth":"2002-04","email":"linxy@example.com","phone":"138 0000 0014","photo":"","years":"0","intent":"应届求职（结构/工艺方向）"},"work":[{"end":"2023-09","role":"工艺实习生","start":"2023-06","bullets":["参与 2 条装配线作业指导书修订，工位节拍记录 300+ 次","协助整理工装图纸 45 份，建立电子归档目录"],"company":"某制造企业"},{"end":"2023-05","role":"设计助理（实习）","start":"2023-01","bullets":["完成 12 个零件三维建模与出图，导师一次审核通过率 90%"],"company":"某设计公司"}],"certs":[{"org":"示例","date":"2022-06","name":"CET-6"}],"links":[],"awards":["校级二等奖学金（示例）"],"skills":[{"name":"SolidWorks","level":80},{"name":"AutoCAD","level":78},{"name":"英语 CET-6","level":75}],"summary":"机械专业应届本科，两段制造相关实习与一个完整毕业设计，能读图、建模、做样机并记录数据。示例文字，请换成你自己的经历。","projects":[{"end":"2024-05","desc":"以有限元分析减重 15%，答辩成绩良好（示例）","name":"毕业设计：可折叠搬运车结构优化","role":"独立完成","start":"2023-10"},{"end":"2022-11","desc":"作品获省级二等奖，负责结构方案与样机装配（示例）","name":"全国大学生机械创新设计大赛","role":"团队第二负责人","start":"2022-03"}],"education":[{"end":"2024-06","note":"GPA 3.5/4.0，专业前 20%；主修机械原理、机械设计、工程材料（示例）","major":"机械设计制造及其自动化","start":"2020-09","degree":"本科","school":"浙江理工大学"}],"skillTags":["工程制图","三维建模","样机制作","数据记录","团队协作"]}$rqjson$::jsonb, $rqjson${"lh":1.6,"dens":1,"font":"sans","head":"underline","style":"timeline","accent":"#2f5c8f","layout":"default","timeline":true}$rqjson$::jsonb, 140),
  ('electrical-engineer', '电气工程师', '制造业', '写清电气设计、PLC/传动、选型与安规认证、现场调试量与降本。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"苏州","name":"孙立","site":"","birth":"1992-05","email":"sunli@example.com","phone":"138 0000 0021","photo":"","years":"9","intent":"电气工程师"},"work":[{"end":"至今","role":"电气主管","start":"2018-03","bullets":["主导 30+ 条自动化产线电气设计与 PLC 程序，节拍平均提升 18%（示例）","建立元器件选型库与 BOM 标准，电气成本单线下降约 12%","完成 CE/UL 安规整改 8 项，设备出口零安规退货"],"company":"某智能装备有限公司"},{"end":"2018-02","role":"电气工程师","start":"2014-07","bullets":["负责伺服/变频传动选型与调试，故障停机时间下降 40%","编写点检与保养 SOP，一线电工 12 人按图作业"],"company":"某汽车零部件公司"}],"certs":[{"org":"示例","date":"2017-06","name":"注册电气工程师（供配电）"}],"links":[],"awards":["改善提案一等奖（示例）"],"skills":[{"name":"PLC（西门子）","level":90},{"name":"EPLAN 电气制图","level":85},{"name":"伺服/变频传动","level":82}],"summary":"9 年自动化设备电气设计经验，从方案、绘图、选型到 PLC 调试与安规认证可独立完成；擅长用标准化降本。示例文字。","projects":[{"end":"2023-08","desc":"整线电气 BOM 成本降 15%，年省约 200 万元（示例）","name":"多条装配线电气标准化","role":"电气负责人","start":"2023-01"}],"education":[{"end":"2014-06","note":"示例","major":"电气工程及其自动化","start":"2010-09","degree":"本科","school":"江苏大学"}],"skillTags":["PLC","EPLAN","伺服","变频器","安规CE/UL","电气BOM"]}$rqjson$::jsonb, $rqjson${"lh":1.55,"dens":1,"font":"sans","head":"underline","style":"blueprint","accent":"#1f6f8f","layout":"default"}$rqjson$::jsonb, 150),
  ('equipment-engineer', '设备工程师', '制造业', '写设备选型、安装调试、稼动率(OEE)、备件与故障率改善。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"青岛","name":"马涛","site":"","birth":"1990-09","email":"matao@example.com","phone":"138 0000 0022","photo":"","years":"11","intent":"设备工程师"},"work":[{"end":"至今","role":"设备工程师","start":"2016-04","bullets":["负责 200+ 台生产设备台账与维护，综合 OEE 由 68% 提升至 82%（示例）","推行 TPM 点检与预防保养，非计划停机次数下降 55%","主导 6 台关键设备国产化改造，备件成本年省 45 万"],"company":"某精密制造企业"},{"end":"2016-03","role":"设备技术员","start":"2011-07","bullets":["跟踪新设备 FAT/SAT 验收，装机到量产周期缩短 20 天"],"company":"某家电集团"}],"certs":[{"org":"示例","date":"2015-05","name":"机械设备安装工（高级）"}],"links":[],"awards":[],"skills":[{"name":"TPM/点检体系","level":88},{"name":"气动液压","level":82},{"name":"PLC 排故","level":78}],"summary":"11 年制造现场设备管理经验，从选型、安装到稼动率提升与备件国产化都能落地；用数据看设备健康。示例文字。","projects":[{"end":"2022-10","desc":"核心工序 OEE 提升 9 个百分点（示例）","name":"注塑机节能与快换模改造","role":"项目负责人","start":"2022-03"}],"education":[{"end":"2011-06","note":"示例","major":"机械设计制造及其自动化","start":"2007-09","degree":"本科","school":"青岛科技大学"}],"skillTags":["TPM","OEE","FAT/SAT","备件国产化","快换模"]}$rqjson$::jsonb, $rqjson${"lh":1.55,"dens":1,"font":"sans","head":"underline","style":"blueprint","accent":"#1f6f8f","layout":"default"}$rqjson$::jsonb, 160),
  ('ie-engineer', '工业工程师 IE', '制造业', '写标准工时、产线平衡、精益改善与人均产出提升。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"东莞","name":"方敏","site":"","birth":"1993-03","email":"fangmin@example.com","phone":"138 0000 0023","photo":"","years":"7","intent":"工业工程师（IE）"},"work":[{"end":"至今","role":"IE 工程师","start":"2019-06","bullets":["完成 15 条产线标准工时与线平衡，瓶颈工位稼动率提升 22%（示例）","主导某品类价值流(VSM)改善，在制品下降 30%","建立人效看板，人均产出同比提升 16%"],"company":"某电子制造企业"},{"end":"2019-05","role":"IE 技术员","start":"2016-07","bullets":["动作分析与工位改善 60+ 项，累计节省 8000 工时"],"company":"某五金制品厂"}],"certs":[{"org":"示例","date":"2018-11","name":"精益生产绿带"}],"links":[],"awards":[],"skills":[{"name":"标准工时/动作分析","level":90},{"name":"产线平衡","level":85},{"name":"VSM 价值流","level":80}],"summary":"7 年 IE/精益经验，从工时测定、线平衡到价值流改善闭环推进；一切用数据量化产出与浪费。示例文字。","projects":[{"end":"2023-05","desc":"某线换型时间由 45 分钟降至 12 分钟（示例）","name":"SMED 快速换模专案","role":"主导","start":"2022-11"}],"education":[{"end":"2016-06","note":"示例","major":"工业工程","start":"2012-09","degree":"本科","school":"广东工业大学"}],"skillTags":["标准工时","线平衡","VSM","SMED","精益绿带","人效看板"]}$rqjson$::jsonb, $rqjson${"lh":1.55,"dens":1,"font":"sans","head":"bar","style":"donut","accent":"#4a3f8f","layout":"default"}$rqjson$::jsonb, 170),
  ('cost-engineer', '造价员 / 施工员', '建筑地产', '写图纸算量、清单组价、进度与现场签证、成本偏差控制。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"成都","name":"袁野","site":"","birth":"1994-02","email":"yuanye@example.com","phone":"138 0000 0024","photo":"","years":"6","intent":"土建造价员"},"work":[{"end":"至今","role":"土建造价","start":"2020-08","bullets":["独立完成 12 个项目土建算量与清单组价，累计产值约 3.2 亿元（示例）","施工图预算与结算对比偏差控制在 3% 以内","现场签证与变更台账规范化，追回漏项约 180 万"],"company":"某建设工程公司"},{"end":"2020-07","role":"施工员","start":"2018-07","bullets":["负责 3 栋主体结构施工放线与进度，节点达成率 100%"],"company":"某建筑施工总包"}],"certs":[{"org":"示例","date":"2021-09","name":"一级造价工程师（土建）"}],"links":[],"awards":[],"skills":[{"name":"广联达算量","level":90},{"name":"清单计价","level":85},{"name":"CAD 读图","level":82}],"summary":"6 年造价与施工一线经验，土建算量、清单组价、现场签证全流程熟悉；重数据与合同口径一致。示例文字。","projects":[],"education":[{"end":"2018-06","note":"示例","major":"工程管理","start":"2014-09","degree":"本科","school":"四川建筑职业技术学院"}],"skillTags":["广联达","清单计价","现场签证","进度款","结算"]}$rqjson$::jsonb, $rqjson${"lh":1.55,"dens":1,"font":"sans","head":"underline","style":"blueprint","accent":"#1f6f8f","layout":"default"}$rqjson$::jsonb, 180),
  ('product-manager', '产品经理', '互联网/IT', '写负责的产品/模块、需求与数据驱动决策、上线后的核心指标提升。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"杭州","name":"陈屿","site":"","birth":"1993-07","email":"chenyu@example.com","phone":"138 0000 0031","photo":"","years":"6","intent":"B 端产品经理"},"work":[{"end":"至今","role":"产品经理","start":"2020-05","bullets":["负责 SaaS 订单模块，从 0 到 1 上线，付费客户 3 个月增长 2.4 倍（示例）","主导需求评审与数据埋点，核心流程转化率从 41% 提升至 63%","协同研发/设计/客户成功双周迭代，需求交付准时率 92%"],"company":"某企业服务公司"},{"end":"2020-04","role":"产品助理","start":"2018-07","bullets":["整理 200+ 客户反馈进需求池，推动 30 项高频优化上线"],"company":"某电商平台"}],"certs":[],"links":[],"awards":[],"skills":[{"name":"需求分析/PRD","level":88},{"name":"SQL 取数","level":80},{"name":"数据分析","level":82}],"summary":"6 年 B 端产品经验，擅长把业务问题拆成可上线的方案并用数据验证；从需求到交付全链路自己能跑。示例文字。","projects":[{"end":"2023-09","desc":"客户工单量下降 35%（示例）","name":"订单异常自助化处理","role":"产品负责人","start":"2023-02"}],"education":[{"end":"2018-06","note":"示例","major":"信息管理","start":"2014-09","degree":"本科","school":"浙江工业大学"}],"skillTags":["PRD","数据埋点","SQL","A/B 测试","用户访谈","路线图"]}$rqjson$::jsonb, $rqjson${"lh":1.55,"dens":1,"font":"sans","head":"bar","style":"donut","accent":"#4a3f8f","layout":"default"}$rqjson$::jsonb, 190),
  ('frontend-engineer', '前端开发工程师', '互联网/IT', '写技术栈、负责系统、性能优化幅度与工程化产出。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"深圳","name":"何川","site":"github.com/example","birth":"1995-01","email":"hechuan@example.com","phone":"138 0000 0032","photo":"","years":"5","intent":"前端开发工程师"},"work":[{"end":"至今","role":"前端工程师","start":"2021-03","bullets":["负责中后台系统前端，首屏加载由 3.2s 优化至 1.1s（示例）","搭建组件库，业务页开发效率提升 40%","推动 CI 与 ESLint 规范，线上 JS 报错率下降 62%"],"company":"某互联网公司"},{"end":"2021-02","role":"前端开发","start":"2019-07","bullets":["完成活动页与 H5 模板化，活动上线周期缩短一半"],"company":"某电商公司"}],"certs":[],"links":[],"awards":[],"skills":[{"name":"React / TypeScript","level":90},{"name":"性能优化","level":84},{"name":"工程化 / Vite","level":80}],"summary":"5 年前端经验，熟悉 React/TS 全家桶与性能优化，重视工程化与可维护性。示例文字。","projects":[{"end":"2023-06","desc":"构建耗时下降 55%（示例）","name":"Monorepo 工程改造","role":"主导","start":"2023-01"}],"education":[{"end":"2019-06","note":"示例","major":"软件工程","start":"2015-09","degree":"本科","school":"华南理工大学"}],"skillTags":["React","TypeScript","Vite","性能优化","组件库","CI"]}$rqjson$::jsonb, $rqjson${"lh":1.6,"dens":1,"font":"mono","head":"plain","style":"terminal","accent":"#39d353","layout":"default"}$rqjson$::jsonb, 200),
  ('algorithm-engineer', '算法工程师', '互联网/IT', '写模型/方向、业务场景、离线与在线指标提升、上线收益。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"北京","name":"唐霖","site":"","birth":"1994-11","email":"tanglin@example.com","phone":"138 0000 0033","photo":"","years":"6","intent":"推荐算法工程师"},"work":[{"end":"至今","role":"算法工程师","start":"2020-09","bullets":["负责首页推荐召回与精排，线上点击率提升 14%（示例）","构建特征平台，特征上线周期从周级降至天级","优化排序模型结构，AUC 由 0.71 提升至 0.76"],"company":"某内容平台"},{"end":"2020-08","role":"数据挖掘","start":"2018-07","bullets":["搭建用户分层与流失预警模型，召回率 82%"],"company":"某金融科技公司"}],"certs":[],"links":[],"awards":["顶会论文一篇（示例）"],"skills":[{"name":"Python / PyTorch","level":90},{"name":"推荐系统","level":86},{"name":"特征工程","level":84}],"summary":"6 年推荐/数据挖掘经验，从特征、模型到线上 A/B 闭环负责，用业务指标而非只看离线分。示例文字。","projects":[{"end":"2023-08","desc":"GMV 提升 6%（示例）","name":"多目标排序优化","role":"核心贡献","start":"2022-12"}],"education":[{"end":"2018-06","note":"示例","major":"计算机应用技术","start":"2015-09","degree":"硕士","school":"北京邮电大学"}],"skillTags":["推荐系统","PyTorch","AUC","A/B 实验","特征工程","召回/排序"]}$rqjson$::jsonb, $rqjson${"lh":1.6,"dens":1,"font":"mono","head":"plain","style":"terminal","accent":"#39d353","layout":"default"}$rqjson$::jsonb, 210),
  ('qa-engineer', '软件测试工程师', '互联网/IT', '写测试类型、自动化覆盖率、缺陷拦截与线上事故下降。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"上海","name":"苏晴","site":"","birth":"1995-06","email":"suqing@example.com","phone":"138 0000 0034","photo":"","years":"5","intent":"测试开发工程师"},"work":[{"end":"至今","role":"测试开发工程师","start":"2020-07","bullets":["搭建接口自动化框架，核心用例自动化覆盖率从 15% 提升至 68%（示例）","接入 CI 流水线，回归测试耗时由 2 天缩短至 2 小时","上线前拦截高危缺陷 40+，线上事故同比下降 50%"],"company":"某互联网公司"},{"end":"2020-06","role":"功能测试","start":"2019-07","bullets":["负责支付模块测试与用例库沉淀，用例复用率提升"],"company":"某电商公司"}],"certs":[],"links":[],"awards":[],"skills":[{"name":"接口/自动化测试","level":88},{"name":"Python","level":80},{"name":"性能测试","level":75}],"summary":"5 年测试开发经验，能把重复回归做成自动化并接入流水线，关注缺陷拦截率而非用例数量。示例文字。","projects":[{"end":"2023-05","desc":"回归效率提升 8 倍（示例）","name":"UI 自动化平台搭建","role":"主导","start":"2022-10"}],"education":[{"end":"2019-06","note":"示例","major":"软件工程","start":"2015-09","degree":"本科","school":"上海大学"}],"skillTags":["接口自动化","Pytest","CI 流水线","性能测试","缺陷管理"]}$rqjson$::jsonb, $rqjson${"lh":1.6,"dens":1,"font":"mono","head":"plain","style":"terminal","accent":"#39d353","layout":"default"}$rqjson$::jsonb, 220),
  ('ecommerce-ops', '电商运营', '商贸服务', '写店铺/GMV、流量结构、活动策划与 ROI、复购。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"杭州","name":"柳青","site":"","birth":"1995-10","email":"liuqing@example.com","phone":"138 0000 0041","photo":"","years":"5","intent":"电商运营（天猫/抖音）"},"work":[{"end":"至今","role":"运营主管","start":"2021-04","bullets":["负责旗舰店运营，年 GMV 由 800 万做到 2400 万（示例）","优化付费/自然流量结构，整体 ROI 从 2.1 提升至 3.4","策划大促与会员体系，复购率提升 18%"],"company":"某品牌电商公司"},{"end":"2021-03","role":"运营专员","start":"2019-07","bullets":["负责详情页与短视频投放，转化率提升 25%"],"company":"某贸易公司"}],"certs":[],"links":[],"awards":["年度优秀团队（示例）"],"skills":[{"name":"数据后台分析","level":86},{"name":"付费推广(直通车)","level":82},{"name":"活动策划","level":80}],"summary":"5 年电商运营经验，从流量、转化到复购用数据驱动；擅长把预算花在能带来 GMV 的地方。示例文字。","projects":[{"end":"2023-11","desc":"双十一单日 GMV 破 300 万（示例）","name":"大促全案运营","role":"项目负责人","start":"2023-09"}],"education":[{"end":"2019-06","note":"示例","major":"电子商务","start":"2015-09","degree":"本科","school":"浙江工商大学"}],"skillTags":["直通车","超级推荐","GMV","ROI","会员复购","直播投流"]}$rqjson$::jsonb, $rqjson${"lh":1.58,"dens":1,"font":"sans","head":"bar","style":"voyage","accent":"#117a65","layout":"default"}$rqjson$::jsonb, 230),
  ('content-ops', '新媒体 / 直播运营', '商贸服务', '写账号矩阵、粉丝/播放增长、爆款率、直播间转化与 GMV。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"长沙","name":"田夏","site":"","birth":"1997-03","email":"tianxia@example.com","phone":"138 0000 0042","photo":"","years":"4","intent":"新媒体 / 直播运营"},"work":[{"end":"至今","role":"内容运营","start":"2022-01","bullets":["操盘抖音账号矩阵，半年粉丝从 0 做到 50 万（示例）","打造 8 条百万播放爆款，直播间平均停留提升 40%","主导日播 6 小时，单场最高 GMV 80 万"],"company":"某 MCN / 品牌自营"},{"end":"2021-12","role":"短视频运营","start":"2020-07","bullets":["脚本—拍摄—剪辑全流程，周更 12 条，账号涨粉 15 万"],"company":"某电商公司"}],"certs":[],"links":[],"awards":[],"skills":[{"name":"短视频编导","level":88},{"name":"直播操盘","level":82},{"name":"数据分析","level":78}],"summary":"4 年新媒体/直播运营，从选题脚本到投放与直播节奏都能上手，用后台数据迭代内容而非凭感觉。示例文字。","projects":[{"end":"2023-12","desc":"新号冷启动 3 个月破 20 万粉（示例）","name":"品牌自播体系搭建","role":"主导","start":"2023-06"}],"education":[{"end":"2020-06","note":"示例","major":"网络与新媒体","start":"2016-09","degree":"本科","school":"湖南师范大学"}],"skillTags":["抖音","视频号","直播投流","爆款选题","剪映","千川"]}$rqjson$::jsonb, $rqjson${"lh":1.58,"dens":1,"font":"sans","head":"bar","style":"voyage","accent":"#117a65","layout":"default"}$rqjson$::jsonb, 240),
  ('service-supervisor', '客服 / 售后主管', '商贸服务', '写团队规模、响应时效、满意度、投诉闭环与降本。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"南京","name":"钟颖","site":"","birth":"1992-12","email":"zhongying@example.com","phone":"138 0000 0043","photo":"","years":"8","intent":"客服 / 售后主管"},"work":[{"end":"至今","role":"客服主管","start":"2019-05","bullets":["带 25 人客服团队，一次解决率由 72% 提升至 90%（示例）","首响时长压缩至 28 秒，客户满意度 4.8/5","搭建知识库与话术，新人培训周期缩短一半","退款纠纷闭环处理，投诉升级率下降 45%"],"company":"某电商集团"},{"end":"2019-04","role":"客服组长","start":"2015-07","bullets":["负责大促排班与峰值承接，超时率归零"],"company":"某品牌商"}],"certs":[],"links":[],"awards":["金牌管理者（示例）"],"skills":[{"name":"团队管理","level":86},{"name":"话术/知识库","level":84},{"name":"客诉处理","level":88}],"summary":"8 年客服售后经验，重响应时效与一次解决率，用知识库和排班机制把服务做成可复制流程。示例文字。","projects":[],"education":[{"end":"2015-06","note":"示例","major":"工商管理","start":"2011-09","degree":"大专","school":"江苏经贸学院"}],"skillTags":["一次解决率","满意度","知识库","排班","客诉闭环"]}$rqjson$::jsonb, $rqjson${"lh":1.55,"dens":1,"font":"sans","head":"bar","style":"donut","accent":"#4a3f8f","layout":"default"}$rqjson$::jsonb, 250),
  ('hrbp', '人力资源 BP', '商贸服务', '写业务伙伴价值、招聘达成、人效与组织氛围建设。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"武汉","name":"段斐","site":"","birth":"1991-08","email":"duanfei@example.com","phone":"138 0000 0044","photo":"","years":"10","intent":"HRBP"},"work":[{"end":"至今","role":"HRBP","start":"2018-06","bullets":["支持 3 条业务线约 200 人，关键岗位到岗周期由 45 天缩短至 22 天（示例）","搭建人效与离职预警看板，主动离职率下降 9 个百分点","推动干部盘点与继任计划，内部晋升覆盖率 60%"],"company":"某科技公司"},{"end":"2018-05","role":"招聘主管","start":"2013-07","bullets":["年交付到岗 180 人，研发岗交付率 95%"],"company":"某制造企业"}],"certs":[{"org":"示例","date":"2017-05","name":"一级人力资源管理师"}],"links":[],"awards":[],"skills":[{"name":"招聘与人才画像","level":88},{"name":"人效分析","level":82},{"name":"组织与员工关系","level":85}],"summary":"10 年 HR 经验，其中 5 年 BP，贴业务做人才与组织，用数据把 HR 从职能变伙伴。示例文字。","projects":[{"end":"2023-06","desc":"关键人才保留率提升至 92%（示例）","name":"干部梯队建设项目","role":"主导","start":"2022-09"}],"education":[{"end":"2013-06","note":"示例","major":"人力资源管理","start":"2009-09","degree":"本科","school":"华中师范大学"}],"skillTags":["人才画像","人效","继任计划","离职预警","干部盘点"]}$rqjson$::jsonb, $rqjson${"lh":1.55,"dens":1,"font":"sans","head":"underline","style":"sidebar","accent":"#244a75","layout":"sidebar"}$rqjson$::jsonb, 260),
  ('legal-specialist', '法务专员', '专业服务', '写合同审核量、风险拦截、诉讼/仲裁结果与合规体系。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"上海","name":"顾岚","site":"","birth":"1992-04","email":"gulan@example.com","phone":"138 0000 0051","photo":"","years":"7","intent":"公司法务"},"work":[{"end":"至今","role":"法务主管","start":"2019-08","bullets":["年审核合同 600+ 份，重大风险条款拦截 40+ 处（示例）","主导 12 起商事诉讼/仲裁，胜诉或有利和解率 83%","搭建合规与用印流程，纠纷发生率下降 35%"],"company":"某集团公司"},{"end":"2019-07","role":"法务专员","start":"2016-07","bullets":["负责劳动争议处理，仲裁应诉零败诉"],"company":"某制造企业"}],"certs":[{"org":"示例","date":"2016-11","name":"法律职业资格证（A 证）"}],"links":[],"awards":[],"skills":[{"name":"合同审核","level":90},{"name":"诉讼仲裁","level":84},{"name":"合规体系","level":82}],"summary":"7 年公司法务经验，合同、争议、合规三线并进，把风险控在事前而非事后救火。示例文字。","projects":[],"education":[{"end":"2016-06","note":"示例","major":"法学","start":"2012-09","degree":"本科","school":"华东政法大学"}],"skillTags":["合同审核","劳动争议","合规","诉讼仲裁","尽调"]}$rqjson$::jsonb, $rqjson${"lh":1.6,"dens":1,"font":"serif","head":"underline","style":"classic","accent":"#35566b","layout":"default"}$rqjson$::jsonb, 270),
  ('financial-analyst', '财务分析 / FP&A', '专业服务', '写建模、预算、经营分析与降本增效结论。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"上海","name":"汪泽","site":"","birth":"1993-09","email":"wangze@example.com","phone":"138 0000 0052","photo":"","years":"6","intent":"财务分析师（FP&A）"},"work":[{"end":"至今","role":"FP&A","start":"2020-03","bullets":["搭建经营分析模型与月度 BI 看板，为管理层提供 60+ 决策项（示例）","通过产品结构分析推动低毛利 SKU 优化，毛利率提升 3.2 个百分点","滚动预算与偏差分析，费用超支率下降一半"],"company":"某消费品公司"},{"end":"2020-02","role":"财务分析","start":"2018-07","bullets":["建立成本分摊模型，核算口径统一"],"company":"某制造业"}],"certs":[{"org":"示例","date":"2020-09","name":"CMA 注册管理会计师"}],"links":[],"awards":[],"skills":[{"name":"财务建模","level":90},{"name":"BI / SQL","level":82},{"name":"预算管理","level":85}],"summary":"6 年财务分析经验，从核算走向经营支持，用模型和看板把财务数字翻译成业务动作。示例文字。","projects":[],"education":[{"end":"2018-06","note":"示例","major":"财务管理","start":"2014-09","degree":"本科","school":"上海财经大学"}],"skillTags":["财务建模","滚动预算","毛利率分析","Power BI","SQL"]}$rqjson$::jsonb, $rqjson${"lh":1.55,"dens":1,"font":"sans","head":"bar","style":"donut","accent":"#4a3f8f","layout":"default"}$rqjson$::jsonb, 280),
  ('translator', '翻译 / 本地化', '专业服务', '写语种与领域、日均产能、术语库与质检合格率。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"北京","name":"林徽","site":"","birth":"1994-05","email":"linhui@example.com","phone":"138 0000 0053","photo":"","years":"6","intent":"英中翻译 / 本地化"},"work":[{"end":"至今","role":"专职翻译","start":"2019-09","bullets":["承接法律/科技类笔译，日均 3000 字，一次质检通过率 98%（示例）","建立 2 万条术语库，客户术语一致性显著提升","带队完成 3 款 App 多语言本地化并上线"],"company":"某语言服务公司"},{"end":"2019-08","role":"翻译","start":"2018-01","bullets":["合同与专利文件翻译 40+ 万字，零重大差错返稿"],"company":"某翻译工作室"}],"certs":[{"org":"示例","date":"2018-06","name":"CATTI 英语一级笔译"}],"links":[],"awards":[],"skills":[{"name":"CAT 工具(Trados)","level":88},{"name":"术语管理","level":84},{"name":"本地化 QA","level":80}],"summary":"6 年英中翻译与本地化经验，专攻法律与科技文本，靠术语库和质检流程保证一致性。示例文字。","projects":[],"education":[{"end":"2018-06","note":"示例","major":"翻译硕士","start":"2016-09","degree":"硕士","school":"北京外国语大学"}],"skillTags":["Trados","术语库","法律翻译","本地化","CATTI"]}$rqjson$::jsonb, $rqjson${"lh":1.7,"dens":1.05,"font":"serif","head":"plain","style":"minimal","accent":"#1c1c1e","layout":"default"}$rqjson$::jsonb, 290),
  ('teacher', '教师 / 课程顾问', '专业服务', '写带班/课时、提分与升学成果、教研与家校沟通。', $rqjson$[]$rqjson$::jsonb, $rqjson${"base":{"city":"西安","name":"白榆","site":"","birth":"1993-11","email":"baiyu@example.com","phone":"138 0000 0054","photo":"","years":"8","intent":"高中数学教师"},"work":[{"end":"至今","role":"数学教师 / 备课组长","start":"2018-09","bullets":["带 2 个班数学，年级平均分排名长期前 2（示例）","设计分层作业与错题体系，及格率由 76% 提升至 92%","组织教研与青蓝工程，指导 3 位新教师上手"],"company":"某中学"},{"end":"2018-08","role":"教师","start":"2016-09","bullets":["高三毕业班教学，一本上线率提升 12 个百分点"],"company":"某私立学校"}],"certs":[{"org":"示例","date":"2017-05","name":"高级中学教师资格证"}],"links":[],"awards":["区级赛课一等奖（示例）"],"skills":[{"name":"课堂设计","level":90},{"name":"提分策略","level":85},{"name":"家校沟通","level":82}],"summary":"8 年一线教学与备课组管理经验，重分层教学与错题闭环，用过程数据跟踪而不是只盯分数。示例文字。","projects":[{"end":"2023-06","desc":"薄弱班及格率提升 16 个百分点（示例）","name":"错题本 + 周测闭环","role":"主导","start":"2022-09"}],"education":[{"end":"2016-06","note":"示例","major":"数学与应用数学","start":"2012-09","degree":"本科","school":"陕西师范大学"}],"skillTags":["分层教学","错题体系","教研","班主任","中高考"]}$rqjson$::jsonb, $rqjson${"lh":1.5,"dens":1,"font":"serif","head":"underline","style":"magazine","accent":"#7a3f5c","layout":"magazine"}$rqjson$::jsonb, 300)
ON CONFLICT (slug) DO UPDATE SET
  title=EXCLUDED.title, industry=EXCLUDED.industry, summary=EXCLUDED.summary,
  sections=EXCLUDED.sections, sample=EXCLUDED.sample, theme=EXCLUDED.theme, sort=EXCLUDED.sort,
  updated_at=now();

-- 2) 职业词库（按 profession/kind/text 去重更新）
INSERT INTO tpl_glossary (profession,kind,text,weight,source) VALUES
  ('structural-engineer', '成果句式', '通过料重再分布与截面优化，整件重量下降 12%，承载指标仍满足企业标准', 1, 'seed'),
  ('structural-engineer', '成果句式', '建立标准件与型材库，图纸差错率下降 38%，打样轮次平均减少 1.4 次', 1, 'seed'),
  ('structural-engineer', '职责句式', '负责 XX 品类的结构方案设计、图纸输出与 BOM 编制，覆盖从打样到量产导入全流程', 1, 'seed'),
  ('structural-engineer', '职责句式', '参与客户评审与工艺可行性分析（DFM），提前识别装配与模具风险点', 1, 'seed'),
  ('worker', '成果句式', '日均完成 260 件，一次合格率 99.2%，班组不良率由 2.4% 降至 1.1%', 1, 'seed'),
  ('worker', '职责句式', '按图纸与作业指导书完成铝件氩弧焊接与自检，执行首件确认制度', 1, 'seed'),
  ('worker', '成果句式', '参与 3 项工装改善提案，连续 5 年零工伤事故', 1, 'seed'),
  ('worker', '关键词', '工装 节拍 首件自检 图纸识读 安全生产 5S', 1, 'seed'),
  ('accountant', '成果句式', '报表准时率 100%，汇算清缴零调整，配合 4 次外审无重大调整事项', 1, 'seed'),
  ('accountant', '职责句式', '负责全盘账务、月度报表编制、纳税申报与出口退税资料准备', 1, 'seed'),
  ('accountant', '成果句式', '清理长期挂账 260 万元，逾期应收回收率提升至 96%', 1, 'seed'),
  ('accountant', '关键词', '毛利核算 内控 发票管理 成本分摊 税务筹划', 1, 'seed'),
  ('pc-planner', '成果句式', '订单准时交付率由 83% 提升至 96%，缺料停线次数下降 62%', 1, 'seed'),
  ('pc-planner', '职责句式', '编制主生产计划与日派工单，协调物料齐套、产能负荷与交期承诺', 1, 'seed'),
  ('pc-planner', '成果句式', '成品库存周转天数从 34 天降至 21 天，占用资金减少约 300 万元', 1, 'seed'),
  ('pc-planner', '关键词', 'MRP 齐套率 S&OP 瓶颈工序 插单 呆滞料', 1, 'seed'),
  ('warehouse', '成果句式', '账实一致率由 94% 提升至 99.5%，月度盘点差异金额下降 76%', 1, 'seed'),
  ('warehouse', '职责句式', '负责入库验收、库位规划、波次拣货与循环盘点，管理 WMS 数据准确性', 1, 'seed'),
  ('warehouse', '成果句式', '推行 ABC 分区与波次拣货，人均拣货效率提升 35%', 1, 'seed'),
  ('warehouse', '关键词', '先进先出 呆滞 安全库存 装卸 库位 补货', 1, 'seed'),
  ('foreign-sales', '成果句式', '年度成交 780 万美元，新客户 32 家，老客户复购率 68%，坏账为零', 1, 'seed'),
  ('foreign-sales', '职责句式', '负责欧美市场客户开发、报价谈判、订单跟进与结汇回款全链路', 1, 'seed'),
  ('foreign-sales', '成果句式', '单客户获客成本下降 22%，平均回款周期压缩至 26 天', 1, 'seed'),
  ('foreign-sales', '关键词', '询盘转化率 展会 开发信 信用证 年度框架 返利', 1, 'seed'),
  ('qa-qc', '成果句式', '关键工序 CPK 由 1.02 提升至 1.47，客诉件数同比下降 45%', 1, 'seed'),
  ('qa-qc', '职责句式', '负责进料/过程/出货三阶段检验标准制定、客诉处理与 8D 报告闭环', 1, 'seed'),
  ('qa-qc', '成果句式', '焊接不良率由 3.8% 降至 0.9%，年减少返工与报废成本约 30 万元', 1, 'seed'),
  ('qa-qc', '关键词', 'FMEA MSA 8D 5Why 检具 验厂 不符合项', 1, 'seed'),
  ('sales', '成果句式', '年回款 960 万元，指标完成率 118%，区域排名 2/26', 1, 'seed'),
  ('sales', '职责句式', '负责区域经销商开发、招投标跟进、合同签订与回款管理', 1, 'seed'),
  ('sales', '成果句式', '新开经销商 19 家，老客户续约率 74%，客单价提升 54%', 1, 'seed'),
  ('sales', '关键词', '漏斗转化 陌生拜访 回款 渠道 推介会 CRM', 1, 'seed'),
  ('pm', '成果句式', '并行 6 个项目、合同额 4200 万元，按期交付率 92%，毛利率超目标 4.6 个百分点', 1, 'seed'),
  ('pm', '职责句式', '负责项目 WBS 分解、里程碑计划、预算与风险登记，跨部门拉通交付', 1, 'seed'),
  ('pm', '成果句式', '重大变更响应周期由 7 天压缩至 2 天，团队人力利用率提升至 88%', 1, 'seed'),
  ('pm', '关键词', '里程碑 挣值 干系人 变更单 风险登记册', 1, 'seed'),
  ('hr-admin', '成果句式', '一线岗位到岗周期由 21 天压缩至 11 天，年到岗 130 人', 1, 'seed'),
  ('hr-admin', '职责句式', '负责招聘渠道维护、面试组织、入离职手续与考勤薪酬核算', 1, 'seed'),
  ('hr-admin', '成果句式', '主动离职率下降 8 个百分点，月度薪酬核算差错归零', 1, 'seed'),
  ('hr-admin', '关键词', '社保公积金 劳动合同 绩效台账 培训 员工关系', 1, 'seed'),
  ('buyer', '成果句式', '年采购额 1.6 亿元实现综合降本 6.8%，双源覆盖率提升至 82%', 1, 'seed'),
  ('buyer', '职责句式', '负责五金、型材与粉末涂料等品类询比价、供应商评审与年度框架签订', 1, 'seed'),
  ('buyer', '成果句式', '来料准时率提升至 96%，批次不良率控制在 0.7% 以内', 1, 'seed'),
  ('buyer', '关键词', '成本拆解 账期 VMI 供应商考核 价格波动', 1, 'seed'),
  ('mold-designer', '成果句式', '导入回弹补偿后试模次数由 4.2 次降至 2.1 次，模具开发周期缩短 15 天', 1, 'seed'),
  ('mold-designer', '职责句式', '独立完成冲压模具结构设计、排样计算与标准件选用，跟进试模与改模', 1, 'seed'),
  ('mold-designer', '成果句式', '沉淀镶件与快换结构方案，同类模具设计工时下降 25%', 1, 'seed'),
  ('mold-designer', '关键词', '连续模 单工程模 板厚 CAE 回弹 镶件 试模 DFM', 1, 'seed'),
  ('doc-clerk', '成果句式', '年制单 1200+ 份，一次审单通过率 99.3%，实现零不符点拒付', 1, 'seed'),
  ('doc-clerk', '职责句式', '制作品发票、装箱单、产地证与信用证交单单据，并跟踪出运各节点', 1, 'seed'),
  ('doc-clerk', '成果句式', '拦截信用证软条款 11 处，避免潜在拒付损失', 1, 'seed'),
  ('doc-clerk', '关键词', 'UCP600 软条款 议付 电放 舱单 报关单', 1, 'seed'),
  ('fresh-grad', '成果句式', '以有限元分析支撑结构减重 15%，毕业设计答辩成绩良好', 1, 'seed'),
  ('fresh-grad', '成果句式', '团队参加省级机械创新设计大赛获二等奖，负责结构方案与样机装配', 1, 'seed'),
  ('fresh-grad', '职责句式', '作为实习生参与作业指导书修订与工位节拍记录，独立完成图纸整理归档', 1, 'seed'),
  ('fresh-grad', '关键词', 'GPA 奖学金 竞赛 实习 项目 社团 数据记录', 1, 'seed')
ON CONFLICT (profession,kind,md5(text)) DO UPDATE SET
  weight=EXCLUDED.weight, source=EXCLUDED.source, updated_at=now();

-- 3) 站点 meta（风格集/规模/版本等）
INSERT INTO tpl_meta (key,value) VALUES
  ('style_sets', $rqjson${"styles":8}$rqjson$::jsonb),
  ('glossary_size', $rqjson${"rows":56}$rqjson$::jsonb),
  ('tpl_synced_at', $rqjson${"at":"2026-09-04 03:05"}$rqjson$::jsonb),
  ('schema_version', $rqjson${"v":1}$rqjson$::jsonb),
  ('profession_size', $rqjson${"rows":14}$rqjson$::jsonb)
ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value, updated_at=now();

COMMIT;
